apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aztec-gh-exporter.fullname" . }}-secret
  labels:
    {{- include "aztec-gh-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  github-token: {{ .Values.env.GITHUB_TOKEN | b64enc }}

